
#include "Core/BoidDelegates.h"


namespace BoidsDelegates
{
	FOnBoidColorUpdateEvent OnBoidColorUpdate;
	FOnBoidNumberUpdateEvent OnBoidNumberUpdate;
	FOnBoidNumberUpdateFinishEvent OnBoidNumberUpdateFinish;
	
	FOnBoidForceParametersChangeEvent OnBoidForceParametersChange;
	FOnBoidSpatialAwarenessParametersChangeEvent OnBoidSpatialAwarenessParametersChange;
	FOnBoidCollisionMultiplierUpdateEvent OnBoidCollisionMultiplierChange;
}
